### ISSUE TITLE
Backendの状況を整理する

### ISSUE THREAD

**Issue by fumontr** [furiko/hack-day-2022#7]
# 概要
GAEのインスタンス料金の関係で、現状BackendのProdを停止している。これを復活させないとBackendを叩く処理が少しでも入っている場合、そこでエラーになって落ちる。（はず）
料金が高い原因はWebsocketを利用したGAEのインスタンスが起動時間に対して課金されることなので、別途安上がりな方法を検討する必要がありそう。REST APIを別に切り出して、単体で立てるのもあり。（2人プレイしない場合、Backendに役割があるかは不明）

## TODO
- [x] GAEの代替候補を検討
- [x] Websocket, HTTPでサーバを別に立てるかどうか検討
- [x] 現在のBackendの状況を共有

**Comment by takapiro99** [comment]
> （2人プレイしない場合、Backendに役割があるかは不明）

「ひとりで遊ぶ」だと、フロントエンドで完結しますね…

**Comment by fumontr** [comment]
マルチプレイに対応するためにWebsocketサーバを安く建てられるところを探さないと〜！

**Comment by takapiro99** [comment]
20部屋まで無料（SaaS(PaaS?)）
https://www.scaledrone.com/pricing

100部屋まで無料っぽい
https://pusher.com/channels/pricing

バックエンドいらなくなっちゃうかもしれないけど、実現はできそう

**Comment by fumontr** [comment]
この辺試してみるか。
一通りBackendの状況とかまとめてREAEMEとか更新しとく。

**Comment by fumontr** [comment]
>  Websocket, HTTPでサーバを別に立てるかどうか検討
現状いらない。Futureワークとして何かバックエンドで管理したいものが出てきたら再度検討。

**Comment by fumontr** [comment]
現状も書いたのでClose！
d6713f1d5f385db59a814d9b3a839b6e6f359566
